import { describe, expect, it } from "vitest";
import * as fs from "node:fs";
import * as path from "node:path";
import { createHash } from "node:crypto";
import { Chess } from "chess.js";
import { buildThreatTree, forcingMoves } from "../threatTree";

/**
 * The threat tree, byte for byte, over every position of the ten real games.
 *
 * buildThreatTree(fenBefore, 2) is on the turn-1 critical path (the contract
 * builder's threats), so a change to how it finds or ranks threats changes
 * what every review is told. The hashes were generated by running this file
 * before forcingMoves was split out of findOpponentThreats
 * (GOLDEN_WRITE=<path> writes them instead of comparing), so a refactor that
 * moves any tree fails here. About 80 seconds of CPU in all: a depth-2 tree
 * reads every reply to every defence.
 */

const GOLDEN = path.join(__dirname, "fixtures/threatTree-golden.json");
const REAL = path.join(
  process.cwd(),
  "src/lib/contract/__tests__/fixtures-real"
);
const FIXTURES = fs
  .readdirSync(REAL)
  .filter((f) => f.endsWith(".json"))
  .sort();

const sha = (v: unknown) =>
  createHash("sha256").update(JSON.stringify(v)).digest("hex").slice(0, 20);

/** Every position a fixture's game reaches, from the start, until a move fails to replay. */
function positionsOf(fixture: string): string[] {
  const fx = JSON.parse(fs.readFileSync(path.join(REAL, fixture), "utf8"));
  const g = new Chess();
  const fens = [g.fen()];
  for (const m of fx.moveHistory as string[]) {
    try {
      g.move(m);
    } catch {
      break;
    }
    fens.push(g.fen());
  }
  return fens;
}

function treeHashes(fixture: string): Record<string, string> {
  const out: Record<string, string> = {};
  positionsOf(fixture).forEach((fen, i) => {
    out[`${fixture}:${i}`] = sha(buildThreatTree(fen, 2));
  });
  return out;
}

describe("buildThreatTree golden", () => {
  if (process.env.GOLDEN_WRITE) {
    it("writes the hashes", () => {
      const all = Object.assign({}, ...FIXTURES.map(treeHashes));
      fs.writeFileSync(
        process.env.GOLDEN_WRITE!,
        JSON.stringify(all, null, 1) + "\n"
      );
    }, 600_000);
    return;
  }

  const golden: Record<string, string> = JSON.parse(
    fs.readFileSync(GOLDEN, "utf8")
  );

  it("pins every position of every real game", () => {
    const count = FIXTURES.reduce((n, f) => n + positionsOf(f).length, 0);
    expect(FIXTURES).toHaveLength(10);
    expect(Object.keys(golden)).toHaveLength(count);
  });

  for (const fixture of FIXTURES) {
    it(`${fixture}: every position builds the tree it built before`, () => {
      const expected = Object.fromEntries(
        Object.entries(golden).filter(([k]) => k.startsWith(`${fixture}:`))
      );
      expect(treeHashes(fixture)).toEqual(expected);
    }, 300_000);
  }
});

describe("forcingMoves", () => {
  // White mates on a8 or b8, checks with Bxf7+, and wins the rook on h2.
  const RANKED = "6k1/5ppp/8/8/2B5/5N2/7r/RR2K3 w - - 0 1";

  it("reads the side to move, for Black too", () => {
    const white = forcingMoves("4k3/8/8/8/3q4/8/3R4/4K3 w - - 0 1", Infinity);
    expect(white.map((m) => m.san)).toEqual(["Re2+", "Rxd4"]);
    const black = forcingMoves("4k3/8/8/8/3q4/8/3R4/4K3 b - - 0 1", Infinity);
    expect(black[0].uci).toBe("d4d2");
    expect(black[0].isCheck).toBe(true);
    expect(black.every((m) => m.uci.startsWith("d4"))).toBe(true);
  });

  it("ranks mates before checks before material, and keeps a capture of 200 cp or more", () => {
    const all = forcingMoves(RANKED, Infinity);
    expect(
      all.map((m) => [m.san, m.isMate, m.isCheck, m.materialGainCp])
    ).toEqual([
      ["Ra8#", true, true, 0],
      ["Rb8#", true, true, 0],
      ["Bxf7+", false, true, 100],
      ["Nxh2", false, false, 500],
    ]);
    expect(all[3]).toMatchObject({ captured: "r", capturedSquare: "h2" });
  });

  it("keeps at most `limit`, three by default, as the tree does", () => {
    expect(forcingMoves(RANKED)).toHaveLength(3);
    expect(forcingMoves(RANKED, 1).map((m) => m.san)).toEqual(["Ra8#"]);
    expect(
      forcingMoves(
        "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1",
        Infinity
      )
    ).toEqual([]);
  });

  it("is the tree's own first level, read for the side the tree swaps to", () => {
    const swap = (fen: string) => {
      const parts = fen.split(" ");
      parts[1] = parts[1] === "w" ? "b" : "w";
      parts[3] = "-";
      return parts.join(" ");
    };
    const fens = [
      RANKED,
      ...positionsOf("07_knight_fork.json"),
      ...positionsOf("09_legal_trap_tactics.json"),
    ];
    let compared = 0;
    for (const fen of fens) {
      const level = buildThreatTree(fen, 1).map((n) => ({
        uci: n.threatUci,
        san: n.threatSan,
        captured: n.capturedPiece,
        capturedSquare: n.capturedSquare,
        isCheck: n.isCheck,
        isMate: n.isMate,
        materialGainCp: n.approxMaterialGainCp,
      }));
      expect(level, fen).toEqual(forcingMoves(swap(fen)));
      if (level.length > 0) compared += 1;
    }
    expect(compared).toBeGreaterThan(5);
  });
});
