import { describe, it, expect, beforeEach, afterEach, vi } from "vitest";
import * as fs from "node:fs";
import * as path from "node:path";
import { createHash } from "node:crypto";
import { NextRequest } from "next/server";
import { Chess } from "chess.js";

/**
 * Byte for byte against the code before PR 2.5 (commit 5d592e7).
 *
 * The other route tests compare a request with a flag against the same
 * request without it, in the same build: a change to code both share would
 * pass them. This file pins the model's inputs and the served response to
 * hashes generated by running this same file at 5d592e7
 * (GOLDEN_WRITE=<path> writes them instead of comparing), over the real
 * fixture 07 game with its real stored context: the compact context, the
 * contract, the per-user tail and the legacy condensed context, all built
 * as the review route builds them. Only the session, the context lookup,
 * the providers, the classifier and the data fetch are stubbed.
 *
 * Every turn must match with COACH_PERSPECTIVE off, in both validator wings
 * and on the legacy prompt, a perspective field and phrases included. With
 * it on, every turn that names no side, no owner and no mis-dotted move
 * must match too. The stored compact context is pinned over all ten real
 * fixtures and adversarial evaluations.
 */

const {
  mockLog,
  mockSession,
  mockCallLLM,
  mockGetAnalysisContext,
  mockClassifyQuestion,
  mockFetchDataSources,
} = vi.hoisted(() => ({
  mockLog: { debug: vi.fn(), info: vi.fn(), warn: vi.fn(), error: vi.fn() },
  mockSession: vi.fn(),
  mockCallLLM: vi.fn(),
  mockGetAnalysisContext: vi.fn(),
  mockClassifyQuestion: vi.fn(),
  mockFetchDataSources: vi.fn(),
}));
vi.mock("@/lib/logging", () => ({
  logger: { child: vi.fn(() => mockLog) },
  withRequestContext: (_: string, fn: () => unknown) => fn(),
  extractRequestId: () => "golden",
  logErrorToSentry: vi.fn(),
}));
vi.mock("@/lib/auth/session", () => ({ requireSession: mockSession }));
vi.mock("@/lib/llmProvider", () => ({
  callLLM: mockCallLLM,
  LLMError: class LLMError extends Error {},
  PUBLIC_LLM_ERROR: { message: "x", code: "x" },
  toSafeLLMError: (e: unknown) => e,
}));
vi.mock("@/lib/analysisContextCache", async (orig) => ({
  ...(await orig<object>()),
  getAnalysisContext: mockGetAnalysisContext,
}));
vi.mock("@/lib/server/firebaseAdmin", () => ({
  getAdminFirestore: vi.fn(),
  AdminConfigError: class extends Error {},
  __resetAdminCacheForTests: vi.fn(),
}));
vi.mock("@/lib/mastermind/categorization/categoryClassifier", async (orig) => ({
  ...(await orig<object>()),
  classifyQuestion: mockClassifyQuestion,
}));
vi.mock("@/lib/mastermind/wireValidators", async (orig) => ({
  ...(await orig<object>()),
  fetchDataSources: mockFetchDataSources,
}));

import { __resetMastermindEnvCacheForTests } from "@/env";
import { POST } from "@/app/api/chat/route";
import { buildCompactGameContext } from "@/lib/coach/compactGameContext";
import { buildCoachContract } from "@/lib/contract/builder";
import { toCompactContract } from "@/lib/contract/followUp";
import { selectCardInsights } from "@/lib/prompts/verbalizerPrompt";
import { getCoachChatSystemPromptParts } from "@/lib/prompts/coachChatPrompt";

const GOLDEN = path.join(__dirname, "fixtures/perspective-golden.json");
const REAL = path.join(
  process.cwd(),
  "src/lib/contract/__tests__/fixtures-real"
);

const sha = (v: unknown) =>
  createHash("sha256").update(JSON.stringify(v)).digest("hex").slice(0, 20);

/** Timings vary run to run; everything else must not. */
function stable(v: unknown): unknown {
  if (Array.isArray(v)) return v.map(stable);
  if (v && typeof v === "object") {
    const out: Record<string, unknown> = {};
    for (const [k, x] of Object.entries(v as Record<string, unknown>)) {
      if (/Ms$|^ms$|At$|^timing$|elapsed|latency|duration/.test(k)) continue;
      out[k] = stable(x);
    }
    return out;
  }
  return v;
}

// ── The stored compact context, over every real fixture ──────────────

type Pos = { lines?: Record<string, unknown>[]; bestMove?: string };

function adversarial(ge: { positions: Pos[] }) {
  const clone = () => JSON.parse(JSON.stringify(ge)) as { positions: Pos[] };
  const edit = (f: (p: Pos[]) => void) => {
    const c = clone();
    f(c.positions);
    return c;
  };
  const mid = Math.floor(ge.positions.length / 2);
  return {
    nullCp: edit((p) => {
      if (p[mid]?.lines?.[0]) p[mid].lines![0].cp = null;
    }),
    mates: edit((p) => {
      if (p[mid]?.lines?.[0]) p[mid].lines![0] = { mate: 3, depth: 16, pv: [] };
      if (p[mid + 1]?.lines?.[0])
        p[mid + 1].lines![0] = { mate: -2, depth: 16, pv: [] };
    }),
    sentinel: edit((p) => {
      if (p[mid]?.lines?.[0]) p[mid].lines![0].depth = 0;
    }),
    depthMismatch: (() => {
      const c = edit((p) => {
        if (p[mid]?.lines?.[0]) p[mid].lines![0].depth = 8;
      });
      return { ...c, settings: { depth: 16 } };
    })(),
    garbageBest: edit((p) => {
      if (p[mid]) p[mid].bestMove = "z9z9";
      if (p[mid + 1]) p[mid + 1].bestMove = "N/A";
    }),
  };
}

function compactCases(): Record<string, string> {
  const out: Record<string, string> = {};
  for (const f of fs.readdirSync(REAL).filter((f) => f.endsWith(".json"))) {
    const fx = JSON.parse(fs.readFileSync(path.join(REAL, f), "utf8"));
    for (const colour of ["w", "b", "white", "black", ""])
      out[`${f}:${colour}`] = buildCompactGameContext(
        fx.moveHistory,
        fx.gameEval,
        colour
      );
    out[`${f}:noeval`] = buildCompactGameContext(
      fx.moveHistory,
      undefined,
      "w"
    );
    for (const [name, ge] of Object.entries(adversarial(fx.gameEval)))
      for (const colour of ["w", "b"])
        out[`${f}:${name}:${colour}`] = buildCompactGameContext(
          fx.moveHistory,
          ge as never,
          colour
        );
    const broken = [...fx.moveHistory];
    broken[Math.floor(broken.length / 2)] = "Qxz9";
    out[`${f}:illegal`] = buildCompactGameContext(broken, fx.gameEval, "w");
  }
  return out;
}

// ── The route, over fixture 07 with its real stored context ──────────

const FX = JSON.parse(
  fs.readFileSync(path.join(REAL, "07_knight_fork.json"), "utf8")
);
const MOVES: string[] = FX.moveHistory;
const fenAfter = (n: number) => {
  const g = new Chess();
  for (const m of MOVES.slice(0, n)) g.move(m);
  return g.fen();
};

interface Turn {
  name: string;
  body: Record<string, unknown>;
  /** Names a side, an owner or a mis-dotted move: may differ with the flag on. */
  sided?: boolean;
  /** The coach's draft for this turn, when not the shared one. */
  draft?: string;
}

const HISTORY = [
  { role: "user", content: "why was 8. Nc7+ a mistake?" },
  { role: "assistant", content: "It forks, but 8. Qxc1 wins the queen." },
];
const TURNS: Turn[] = [
  { name: "unanchored", body: { userMessage: "what went wrong?" } },
  { name: "numbered", body: { userMessage: "why was 8. Nc7+ a mistake?" } },
  { name: "move-n", body: { userMessage: "why was move 8 bad?" } },
  { name: "bare-san", body: { userMessage: "was Qxc1 a mistake?" } },
  {
    name: "history",
    body: {
      userMessage: "and what should I study?",
      conversationHistory: HISTORY,
    },
  },
  {
    name: "what-if",
    body: {
      userMessage: "what about 8. Qxc1 instead?",
      clientEvals: {
        index: 14,
        fen: fenAfter(14),
        depth: 12,
        moves: [
          {
            role: "asked",
            uci: "d1c1",
            cp: 251,
            depth: 12,
            pv: ["d1c1", "a8b8"],
          },
          {
            role: "played",
            uci: "b5c7",
            cp: -97,
            depth: 12,
            pv: ["b5c7", "e8d8"],
          },
        ],
      },
    },
  },
  {
    name: "what-if-borrowed-reply",
    body: {
      userMessage: "what about 8. Qxc1 instead?",
      clientEvals: {
        index: 14,
        fen: fenAfter(14),
        depth: 12,
        moves: [
          {
            role: "asked",
            uci: "d1c1",
            cp: 251,
            depth: 12,
            pv: ["d1c1", "a8b8"],
          },
          {
            role: "played",
            uci: "b5c7",
            cp: -97,
            depth: 12,
            pv: ["b5c7", "e8d8"],
          },
        ],
      },
    },
    draft:
      "After 8. Qxc1, 8... Kd8 9. Qg5 keeps White a piece up. Instead of 8. Nc7+, 8. Qxc1 8... Kd8 9. Qg5 keeps the piece. Lesson: take what is hanging.",
  },
  // Pathway 3.5a: two moves compared, generated before the compare
  // existed, where the payload is dropped as "shape". With COACH_COMPARE
  // off it still is.
  {
    name: "compare-payload",
    body: {
      userMessage: "8. Qxc1 or 8. Nd6+?",
      clientEvals: {
        index: 14,
        fen: fenAfter(14),
        depth: 12,
        moves: [
          {
            role: "asked",
            uci: "d1c1",
            cp: 251,
            depth: 12,
            pv: ["d1c1", "a8b8"],
          },
          {
            role: "compared",
            uci: "b5d6",
            cp: -130,
            depth: 12,
            pv: ["b5d6", "e7d6"],
          },
        ],
      },
    },
  },
  { name: "never-played", body: { userMessage: "why was move 60 bad?" } },
  {
    name: "counted-pawns",
    body: { userMessage: "why did I move 3 pawns so early?" },
  },
  {
    name: "field-and-phrase",
    body: {
      userMessage: "from Black's side, what went wrong?",
      perspective: "b",
    },
    sided: true,
  },
  {
    name: "owner",
    body: { userMessage: "why was Black's move 7 bad?" },
    sided: true,
  },
];

const llm = (content: string) => ({
  content,
  inputTokens: 1,
  outputTokens: 1,
  model: "claude-haiku-4-5",
  provider: "anthropic",
});
const DRAFT =
  "8. Nc7+ forks the king and rook, but 8. Qxc1 wins the queen outright. Lesson: before a fork, take what is hanging.";

let calls: Record<string, unknown>[] = [];
let draft = DRAFT;
async function serve(
  turn: Turn,
  /** Takes out what a newer field adds to the response before it is hashed. */
  strip?: (json: { gameAnalysis?: Record<string, unknown> }) => void
) {
  calls = [];
  draft = turn.draft ?? DRAFT;
  const res = await POST(
    new NextRequest("http://x/api/chat", {
      method: "POST",
      body: JSON.stringify({
        contextId: "golden",
        moveIndex: MOVES.length,
        ...turn.body,
      }),
      headers: { "Content-Type": "application/json" },
    })
  );
  const json = await res.json();
  strip?.(json);
  return sha({
    status: res.status,
    calls: calls.map((c) => ({
      system: c.system,
      systemSuffix: c.systemSuffix,
      messages: c.messages,
    })),
    response: stable(json),
  });
}

const MODES = [
  { name: "validators-on", validators: "true", prompt: "" },
  { name: "validators-off", validators: "false", prompt: "" },
  { name: "legacy", validators: "false", prompt: "legacy" },
];

describe("byte for byte as at 5d592e7", () => {
  beforeEach(async () => {
    vi.clearAllMocks();
    vi.stubEnv("COACH_WHATIF_EVALS", "1");
    mockSession.mockResolvedValue({ session: { uid: "u" } });
    mockClassifyQuestion.mockResolvedValue({
      category: "position_analysis",
      confidence: 0.9,
      rationale: "t",
    });
    mockFetchDataSources.mockResolvedValue({
      featureDelta: undefined,
      pieceRoleDiff: [],
      scout: undefined,
      userHistory: undefined,
    });
    mockCallLLM.mockImplementation(async (opts: Record<string, unknown>) => {
      if (opts.outputSchema || /claims/i.test(String(opts.system ?? "")))
        return llm('{"claims":[]}');
      calls.push(opts);
      return llm(draft);
    });
    const contract = await buildCoachContract({
      moveHistory: MOVES,
      gameEval: FX.gameEval,
      playerColor: "w",
      username: FX.username,
      userRating: FX.userRating,
      gameHeaders: FX.gameHeaders,
      identity: { fen: fenAfter(MOVES.length), playerColor: "w" },
    });
    const served = selectCardInsights(contract).map((i) => i.factIdPrefix);
    const parts = getCoachChatSystemPromptParts({
      personalityId: "friendly",
      userRating: FX.userRating,
      username: FX.username,
      playerColorName: "white",
    });
    const stored = {
      contextId: "golden",
      gameContext: "",
      compactGameContext: buildCompactGameContext(MOVES, FX.gameEval, "w"),
      playedMoves: MOVES,
      systemPrompt: `${parts.stable}\n\n${parts.perUser}`,
      systemPromptStable: parts.stable,
      systemPromptSuffix: parts.perUser,
      fewShotExamples: "",
      fen: fenAfter(MOVES.length),
      skillLevel: "intermediate",
      playerColor: "w",
      moveCount: 10,
      createdAt: 0,
      initialAnalysis: "Your review.",
      gameEval: FX.gameEval,
      compactContract: toCompactContract(contract, served),
    };
    mockGetAnalysisContext.mockImplementation(() =>
      JSON.parse(JSON.stringify(stored))
    );
  });

  afterEach(() => {
    vi.unstubAllEnvs();
    __resetMastermindEnvCacheForTests();
  });

  async function routeHashes(flag: string) {
    const out: Record<string, string> = {};
    for (const mode of MODES) {
      vi.stubEnv("MASTERMIND_VALIDATORS_ENABLED", mode.validators);
      vi.stubEnv("COACH_FOLLOWUP_PROMPT", mode.prompt);
      vi.stubEnv("COACH_PERSPECTIVE", flag);
      __resetMastermindEnvCacheForTests();
      for (const turn of TURNS)
        if (flag === "" || !turn.sided)
          out[`${mode.name}:${turn.name}`] = await serve(turn);
    }
    return out;
  }

  it("the stored compact context and the route's inputs and response", async () => {
    const compact = Object.fromEntries(
      Object.entries(compactCases()).map(([k, v]) => [k, sha(v)])
    );
    const route = await routeHashes("");
    if (process.env.GOLDEN_WRITE) {
      fs.writeFileSync(
        process.env.GOLDEN_WRITE,
        JSON.stringify({ compact, route }, null, 1) + "\n"
      );
      return;
    }
    const golden = JSON.parse(fs.readFileSync(GOLDEN, "utf8"));
    expect(compact).toEqual(golden.compact);
    // Flag off: every turn, a side named in the words or the field
    // included.
    expect(route).toEqual(golden.route);
    // Flag on: every turn that names no side, owner or mis-dotted move.
    const on = await routeHashes("1");
    for (const [k, v] of Object.entries(on)) expect(v, k).toBe(golden.route[k]);
    expect(Object.keys(on).length).toBe(
      MODES.length * TURNS.filter((t) => !t.sided).length
    );
  }, 120_000);

  // Pathway 3.1: under COACH_FOLLOWUP_PROMPT=fielded, every turn the plan
  // does not field is the v1 turn, byte for byte. The TURNS it declines
  // here have no anchor; the test after this one covers the other reasons.
  it("a turn the fielded mode does not field is the v1 turn, byte for byte", async () => {
    const golden = JSON.parse(fs.readFileSync(GOLDEN, "utf8"));
    for (const mode of MODES.filter((m) => m.prompt === "")) {
      vi.stubEnv("MASTERMIND_VALIDATORS_ENABLED", mode.validators);
      vi.stubEnv("COACH_FOLLOWUP_PROMPT", "fielded");
      vi.stubEnv("COACH_PERSPECTIVE", "");
      __resetMastermindEnvCacheForTests();
      let declined = 0;
      for (const turn of TURNS) {
        mockLog.info.mockClear();
        const hash = await serve(turn);
        const plan = mockLog.info.mock.calls.find(
          (c) => c[0] === "followup_fielded"
        )?.[1] as { eligible?: boolean } | undefined;
        if (plan && plan.eligible === false) {
          declined += 1;
          expect(hash, `${mode.name}:${turn.name}`).toBe(
            golden.route[`${mode.name}:${turn.name}`]
          );
        }
      }
      expect(declined, mode.name).toBeGreaterThanOrEqual(3);
    }
  }, 120_000);

  // Pathway 3.4: under COACH_INTENT_ROUTER the legacy prompt reads no
  // routing at all, and on the validators-off wing every turn is one move
  // and the v1 turn, byte for byte, once the `routing` echo it adds is
  // taken out. The mocked router answers what the parsers answer, which is
  // no intent, so a turn no rule reads is the default row. The
  // validators-on wing changes its category on purpose, so its identity is
  // proved against the same run's flag-off calls (route.router.test.ts).
  it("with the router on, the legacy prompt is the golden and the validators-off wing is the golden less routing", async () => {
    const golden = JSON.parse(fs.readFileSync(GOLDEN, "utf8"));
    vi.stubEnv("COACH_INTENT_ROUTER", "1");
    vi.stubEnv("COACH_PERSPECTIVE", "");
    const grammars: string[] = [];
    const strip = (json: { gameAnalysis?: Record<string, unknown> }) => {
      const routing = json.gameAnalysis?.routing as
        | { grammar?: string }
        | undefined;
      if (routing) grammars.push(String(routing.grammar));
      delete json.gameAnalysis?.routing;
    };
    for (const mode of MODES.filter((m) => m.name !== "validators-on")) {
      vi.stubEnv("MASTERMIND_VALIDATORS_ENABLED", mode.validators);
      vi.stubEnv("COACH_FOLLOWUP_PROMPT", mode.prompt);
      __resetMastermindEnvCacheForTests();
      for (const turn of TURNS) {
        if (mode.prompt === "legacy") {
          expect(await serve(turn), `${mode.name}:${turn.name}`).toBe(
            golden.route[`${mode.name}:${turn.name}`]
          );
          continue;
        }
        if (turn.sided) continue;
        grammars.length = 0;
        expect(await serve(turn, strip), `${mode.name}:${turn.name}`).toBe(
          golden.route[`${mode.name}:${turn.name}`]
        );
        expect(grammars, `${mode.name}:${turn.name}`).toEqual(["one_move"]);
      }
    }
  }, 120_000);

  // The other reasons the plan declines a turn (a walkthrough, a context
  // with no contract, a turn about the other side), each compared with the
  // v1 turn served in the same run, since the 5d592e7 golden has no entry
  // for them.
  it("a walkthrough, a context with no contract and a turn about the other side are the v1 turn, byte for byte", async () => {
    const stored = mockGetAnalysisContext.getMockImplementation()!;
    const CASES: {
      reason: string;
      turn: Turn;
      perspective: string;
      noContract?: boolean;
    }[] = [
      {
        reason: "walkthrough",
        turn: {
          name: "walkthrough",
          body: { userMessage: "walk me through 8. Nc7+ step by step" },
        },
        perspective: "",
      },
      {
        reason: "no_contract",
        turn: {
          name: "no-contract",
          body: { userMessage: "why was 8. Nc7+ a mistake?" },
        },
        perspective: "",
        noContract: true,
      },
      {
        reason: "other_side",
        turn: {
          name: "other-side",
          body: { userMessage: "why was 7... Qxc1 good?", perspective: "b" },
        },
        perspective: "1",
      },
    ];
    for (const mode of MODES.filter((m) => m.prompt === "")) {
      for (const c of CASES) {
        mockGetAnalysisContext.mockImplementation(() => {
          const ctx = stored() as Record<string, unknown>;
          if (c.noContract) delete ctx.compactContract;
          return ctx;
        });
        vi.stubEnv("MASTERMIND_VALIDATORS_ENABLED", mode.validators);
        vi.stubEnv("COACH_PERSPECTIVE", c.perspective);
        vi.stubEnv("COACH_FOLLOWUP_PROMPT", "");
        __resetMastermindEnvCacheForTests();
        const v1 = await serve(c.turn);
        vi.stubEnv("COACH_FOLLOWUP_PROMPT", "fielded");
        __resetMastermindEnvCacheForTests();
        mockLog.info.mockClear();
        const fielded = await serve(c.turn);
        const plan = mockLog.info.mock.calls.find(
          (x) => x[0] === "followup_fielded"
        )?.[1] as { eligible?: boolean; reason?: string } | undefined;
        expect(plan, `${mode.name}:${c.reason}`).toMatchObject({
          eligible: false,
          reason: c.reason,
        });
        expect(fielded, `${mode.name}:${c.reason}`).toBe(v1);
      }
      mockGetAnalysisContext.mockImplementation(stored);
    }
  }, 120_000);
});
