// === AUTO-CURATED EXAMPLES FROM DATA PIPELINE ===
// Generated by scripts/data-pipeline/04_curate_gold_standard.py
// Source datasets: Icannos/chess_studies, GM_games.pgn

  {
    id: "data-tact-beg-1",
    positionType: "tactical",
    skillLevel: "beginner",
    scenario: "Kasparov, Garry vs Topalov, Veselin — ? — Move 25. Re7+ — FEN: b2r3r/k4p1p/p2q1np1/Np1P4/3p1Q2/P4PPB/1PP4P/1K2R3 w - - 0 25",
    idealResponse: `(Ree): Not 25.Qxd4+ Qb6 26.
Re7+Nd7 27.Rxd7 and Black is winning. (Pam): It is important to play the
moves in the right order, so not 25.Qxd4+ Qb6 26.Re7+ Nd7! (Jongsma):
Another bombshell. 25.Qxd4+ Qb6 26.Re7+ Nd7 and 28...Kb6 would lead to nothing.`,
  },
  {
    id: "data-tact-beg-2",
    positionType: "tactical",
    skillLevel: "beginner",
    scenario: "Janowski,D vs Marshall,F — New York — Move 41. Ne5 — FEN: 8/p2b1nk1/6p1/1p1B2q1/5r2/2P3Np/PP1Q1P2/4R1K1 b - - 3 41",
    idealResponse: `Things get a bit complicated here. Marshall has several possibilities here. The first, more risky plan, is 42...Re4 43.Re3 Nf3+ 44.Rxf3 h2+ 45.Kh1 Qxd2. The second, more cautious plan, is 42...Nc4 43.Qd3 Nxb2, winning a pawn. Then there's the unclear ...Ng4, getting the Knight into the attack.`,
  },
  {
    id: "data-tact-beg-3",
    positionType: "tactical",
    skillLevel: "beginner",
    scenario: "Emanuel Lasker vs Jose Raul Capablanca — Lasker - Capablanca World Championship Match — Move 34. Kd5 — FEN: 8/8/5p2/2k3p1/3pn1P1/7P/r7/2R2KN1 b - - 1 68",
    idealResponse: `White resigned rather than than deal with this extra d pawn supported by every active black piece. After this win, Capablanca basically clinched the title of World Champion.
The game could have continued Rd1 Nf2, Rb1, d3. At that point, Ne4 followed by d2-d1 is unstoppable unless black sacrifices a full piece. [%cal Gd4d1]`,
  },
  {
    id: "data-tact-beg-4",
    positionType: "tactical",
    skillLevel: "beginner",
    scenario: "? vs ? — ? — Move 22. f4 — FEN: r1b3k1/1ppn2pp/p7/3pp3/7q/2PNQP1B/PP2P3/R4RK1 w - - 2 22",
    idealResponse: `22. Be6+ Kh8 23. Rf2. Remember that "check" is a
free move. It's like getting to move twice in a row. 
Always consider the forced moves first. Many Masters
will often stop analysis if they find a satisfactory
continuation along forced lines. Forced lines are a
"sure thing" as opposed to other lines. I also liked
22.Bxd7 Bxd7 23 Qxe4 with the idea of Rf2.`,
  },
  {
    id: "data-tact-int-5",
    positionType: "tactical",
    skillLevel: "intermediate",
    scenario: "Petrosian vs Keres — Budapest — Move 13. Qa5 — FEN: r2q1rk1/p2n1ppp/b4n2/2pp4/1bP1p3/1P2P3/PB1NNPPP/RB1Q1RK1 b - - 3 13",
    idealResponse: `Qa5 looks good at first since Black has a double attack on the White knight. However, it does nothing to increase Black's main advantage of time and space. Furthermore, White has a strong tactic to save the piece. 13... Nb6 would put more pressure on White's position for example 14.cxd5 Qxd5 15. Bxf6 Qxd2 winning material because of the pin at e2.`,
  },
  {
    id: "data-tact-int-6",
    positionType: "tactical",
    skillLevel: "intermediate",
    scenario: "Shamkovich, L vs Chistiakov — Moscow TCh — Move 19. Rfd1 — FEN: r1bk2r1/pp2n3/4p2Q/q1npP3/3B1N2/P1P5/2P2PPP/R4RK1 w - - 3 19",
    idealResponse: `Threatening to attack the d5-pawn with 20.c4. Such forcing threats are the best tactical resource in positions where the opponent has not finished his development. 19.Bxc5 Qxc5 20.Nxe6+ Bxe6 21.Qxe6 is weaker.`,
  },
  {
    id: "data-tact-int-7",
    positionType: "tactical",
    skillLevel: "intermediate",
    scenario: "W28 vs B28 — Analyzed Games — Move 9. b5 — FEN: r2qkb1r/1p1b1ppp/p1n1p3/2ppP3/3P4/2N2N2/PPP2PPP/R1BQR1K1 b kq - 3 9",
    idealResponse: `9. Re1 is pointless. White missed Ne2 with the idea
of c3. This would ensure a permanent (possibly
winning) advantage in pawn structure. At this point
9.... cxd4 is stronger. However, Black's pawn structure
resembles a strong Queenside attack.`,
  },
  {
    id: "data-tact-int-8",
    positionType: "tactical",
    skillLevel: "intermediate",
    scenario: "Shamkovich, L vs Chistiakov — Moscow TCh — Move 19. Rfd1 — FEN: r1bk2r1/pp2n3/4p2Q/q1npP3/3B1N2/P1P5/2P2PPP/R4RK1 w - - 3 19",
    idealResponse: `Threatening to attack the d5-pawn with 20.c4. Such forcing threats are the best tactical resource in positions where the opponent has not finished his development. 19.Bxc5 Qxc5 20.Nxe6+ Bxe6 21.Qxe6 is weaker.`,
  },
  {
    id: "data-tact-int-9",
    positionType: "tactical",
    skillLevel: "intermediate",
    scenario: "Kasparov vs Karpov — World Championship — Move 18. Ne8 — FEN: r4rk1/pp2bppp/2n1qn1B/5N2/8/3BPQ1P/1P4P1/3R1RK1 b - - 3 18",
    idealResponse: `Black defends the g7-square with the knight, but the kingside has become very congested. My advantage in space is the key to winning the game. 18...Ne5 19.Qxb7 Nxd3 20. Nxg7 Qe4 21.Qc7 Ne5 22.Nf5 with a decisive attack for White.`,
  },
  {
    id: "data-tact-int-10",
    positionType: "tactical",
    skillLevel: "intermediate",
    scenario: "Beliavsky, A vs Wells, P — ? — Move 13. Qxb5 — FEN: r2q1b1r/p3kppp/2Q1p3/1n1n4/8/2N2P2/PP3P1P/R1B1K2R w KQ - 2 13",
    idealResponse: `For a short time, the capture 13.Nxb5 aroused some curiosity. The idea is that 12...a6 13.Nd4 is unpleasant for black due to the threat of 14.Bg5+. But the game Zhuravlev-Stecko (USSR 1971), which continued 13...Rb8! 14.Nd4 Qd7 15.Be3 Rxb2 16.Qc4 f6 17.Rd1 Kf7 18.Nb3 Be7, with advantage to black quickly ended the curiosity.`,
  },
  {
    id: "data-tact-int-11",
    positionType: "tactical",
    skillLevel: "intermediate",
    scenario: "W1 vs B1 — Analyzed Games — Move 15. b3 — FEN: r2qr1k1/1bpnbpp1/pp2p2p/n2pP3/3P1P1P/2N1B1P1/PPP1Q2N/1K1R1B1R w - - 1 15",
    idealResponse: `This weakens your king position unnecessarily. Since there 
is no threat, white can play g4! with a strong attack. For 
example, if 15. ... Bxh4 16. Nf3 Be7 17. g5, and white opens 
the h-file to fatal effect, because of mate threats involving 
Qh2. And if black declines white's pawn, white can simply 
play g5, opening up black's king side.`,
  },
  {
    id: "data-tact-adv-12",
    positionType: "tactical",
    skillLevel: "advanced",
    scenario: "Radjabov,T vs Topalov,V — GMA, Wijk aan Zee NED — Move 22. Bh4 — FEN: 3q1rk1/p3bppp/2Q5/3p4/2pP1n2/2R5/PP3PBP/3R2K1 b - - 1 22",
    idealResponse: `This clears the way for ...Qd8-g5 and guards g3 to prevent Rc3-g3, but that rook has already been en prise (...Nf4-e2+) , so it doesn't make as much sense as ...Be7-b4, preventing b2-b3 and threatening to support ...c4-c3. Perhaps what it is really about is ...Nf4-d3 to attack Pf2 and offer White a way to return material that weakens White's back rank.`,
  },
  {
    id: "data-tact-adv-13",
    positionType: "tactical",
    skillLevel: "advanced",
    scenario: "Shamkovich, L vs Prokhorovich — Moscow TCh — Move 8. a3 — FEN: rnbq1k1r/ppp2pp1/4p2p/3pP3/1b1Pn1Q1/2N1B3/PPP2PPP/R3KBNR w KQ - 4 8",
    idealResponse: `The same idea as the previous game. With the pawn sacrifice White can achieve a significant initiative. After 8.Nge2 c5 9.0-0-0 Nxc3 10.Nxc3 Nc6 11.Nb1 c4, Black got the superior position in the old game Spielmann-Vidmar, Vienna 1907. Forget about the c3-pawn - the Chess Terrorist understands the advantages in development and the quick preparation of an attack.`,
  },
  {
    id: "data-tact-adv-14",
    positionType: "tactical",
    skillLevel: "advanced",
    scenario: "Shamkovich, L vs Prokhorovich — Moscow TCh — Move 8. a3 — FEN: rnbq1k1r/ppp2pp1/4p2p/3pP3/1b1Pn1Q1/2N1B3/PPP2PPP/R3KBNR w KQ - 4 8",
    idealResponse: `The same idea as the previous game. With the pawn sacrifice White can achieve a significant initiative. After 8.Nge2 c5 9.0-0-0 Nxc3 10.Nxc3 Nc6 11.Nb1 c4, Black got the superior position in the old game Spielmann-Vidmar, Vienna 1907. Forget about the c3-pawn - the Chess Terrorist understands the advantages in development and the quick preparation of an attack.`,
  },
  {
    id: "data-tact-adv-15",
    positionType: "tactical",
    skillLevel: "advanced",
    scenario: "Beliavsky, A vs Wells, P — ? — Move 13. Qxb5 — FEN: r2q1b1r/p3kppp/2Q1p3/1n1n4/8/2N2P2/PP3P1P/R1B1K2R w KQ - 2 13",
    idealResponse: `For a short time, the capture 13.Nxb5 aroused some curiosity. The idea is that 12...a6 13.Nd4 is unpleasant for black due to the threat of 14.Bg5+. But the game Zhuravlev-Stecko (USSR 1971), which continued 13...Rb8! 14.Nd4 Qd7 15.Be3 Rxb2 16.Qc4 f6 17.Rd1 Kf7 18.Nb3 Be7, with advantage to black quickly ended the curiosity.`,
  },
  {
    id: "data-stra-beg-16",
    positionType: "strategic",
    skillLevel: "beginner",
    scenario: "W18 vs B18 — Analyzed Games — Move 7. Nbd7 — FEN: rnbq1rk1/pp2ppbp/2p2np1/3p4/2PP4/2N1PN2/PP2BPPP/R1BQ1RK1 b - - 3 7",
    idealResponse: `While this plan is sound, white can get a slight pull by 
playing 8. cxd5 cxd5 9. Qb3 e6 (...Nb6 10. Ne5) 10. Bd2, 
and white can gain c-file occupatio first. Probably 
7. ... dxc4 8. Bxc4 Bg4 leads to better chances for equality, 
with the idea of an eventual ...e5 by black.`,
  },
  {
    id: "data-stra-beg-17",
    positionType: "strategic",
    skillLevel: "beginner",
    scenario: "Shirov,A vs Bareev,E — GMA, Wijk aan Zee NED — Move 18. c4 — FEN: r1b2k1r/pp1n1ppp/1q1Np3/3pP3/5P2/8/2PQB1PP/3RK2R w K - 6 18",
    idealResponse: `White has a significant
advantage in development . To make best use of this advantage it is very
important to open the position's files and diagonals! White threatens cxd5, but it's not clear if he still wants to find a way to castle or if he will fight with Ke1 and perhaps Rh1-f1.`,
  },
  {
    id: "data-stra-beg-18",
    positionType: "strategic",
    skillLevel: "beginner",
    scenario: "? vs ? — ���� Sicilian Kan Repertoire ����: Sideline: Closed Sicilian Part 1 (2. Nc3 a6 3. f4) — Move 7. h5 — FEN: rn1qkbnr/1b3ppp/p3p3/1pppP3/5P2/2NP1NP1/PPP4P/R1BQKB1R b KQkq - 0 7",
    idealResponse: `This is a common idea for black whenever white pushes e5. Now the f5 square is weakened and a great spot for the black knight, which will hop in from g8-h6-f5. Black has dominance over all sides of the board, with a potential kingside attack with a well-timed h4, and space advantage on the queenside and center.`,
  },
  {
    id: "data-stra-beg-19",
    positionType: "strategic",
    skillLevel: "beginner",
    scenario: "Bronstein, D vs Shamkovich, L — USSR Championship — Move 32. Ba3 — FEN: 4rrk1/pq4p1/2R5/3PPp2/5N2/1P4P1/PB4K1/4R3 w - - 1 32",
    idealResponse: `After the game, we discovered the shot 32.Rg6!! which comes close to punishing me for the super-optimistic 28...Qh5. But in sharp time pressure, it is never too easy. After 32...Rd8, there is 33.Rd1 Rc8 34.Rd2 Qb4 35.Re2 Rc3! 36.e6 Rfc8 37.Nh5 (37.e7! Kf7 38.Rxg7+ Kxg7 39.e8=Q Rxe8 40.Rxe8 Kf7 41.Bxc3 Qxc3 42.Re2 is equal) 37...Kh7 38.Rxg7+ Kh6 which is unclear; or 33.e6 Rxd5 34.Rxg7+ Qxg7 35.Bxg7 Rd2+ 36.Kf3 Kxg7 37.a4 with a roughly level game.`,
  },
  {
    id: "data-stra-int-20",
    positionType: "strategic",
    skillLevel: "intermediate",
    scenario: "Bronstein, D vs Shamkovich, L — USSR Championship — Move 24. Be4 — FEN: 4rrk1/p5p1/2p1q3/2bpPp2/5Q2/1PN2bP1/PB3P2/2R1R1K1 b - - 0 24",
    idealResponse: `Who is better? Black's ideas include ...Qg6-h5; and ...Be7 followed by ...g5 with a strong attack. But white has serious
pressure along the c-file. True, 25.Nxd5? doesn't work because of 25...Qxd5 26.Red1 Qf7 27.Rxc5 Qh5! winning.`,
  },
  {
    id: "data-stra-int-21",
    positionType: "strategic",
    skillLevel: "intermediate",
    scenario: "Van Wely,L vs Polgar,Ju — GMA, Wijk aan Zee NED — Move 12. Qc8 — FEN: r2q1rk1/pb1pbppp/1p2pn2/2n5/2P2B2/2N2NP1/PPQ1PPBP/R2R2K1 b - - 9 12",
    idealResponse: `defending Bc8 and possibly preparing to pressure Pc4 or less likely ...Qc8-c6 to control the center directly or somewhat likely ...Bb7-c6 and ...Qc8-b7. Black's position looks a little awkward, but the minor pieces have good squares and there aren't any severe weaknesses except d6.`,
  },
  {
    id: "data-stra-int-22",
    positionType: "strategic",
    skillLevel: "intermediate",
    scenario: "Anand, Viswanathan vs Kasparov, Garri — SuperGM — Move 7. Nb3 — FEN: rnbqkb1r/1p3ppp/p2p1n2/4p3/3NP3/2N1B3/PPP2PPP/R2QKB1R w KQkq - 0 7",
    idealResponse: `Now there are a couple of weaknesses in Black's pawn structure, so White will have a clear idea of where to play (d5, d6, b6) . However, Pe5 controls d4 and with ...Bc8-e6 Black controls d5 pretty well too. Only Bf8 will be noticably bad.`,
  },
  {
    id: "data-stra-int-23",
    positionType: "strategic",
    skillLevel: "intermediate",
    scenario: "Janowski,D vs Alekhine,A — New York — Move 13. Qc7 — FEN: 2rq1rk1/pb2ppbp/1pn2np1/6B1/2BP4/P1NQ1N2/1P3PPP/R3R1K1 b - - 2 13",
    idealResponse: `Alekhine creates a battery on the open c-file. He's also increased the scope of the Queen; it now controls space on the h2-b8 diagonal. Most importantly, he's threatening to ruin White's position with 14...Nxd4 15.Qxd4 Qxd4 16.Qxc4 Rxc4 17.Rxe7 Bxf3 18.gxf3.`,
  },
  {
    id: "data-stra-int-24",
    positionType: "strategic",
    skillLevel: "intermediate",
    scenario: "Bogoljubow,E vs Marshall,F — New York — Move 14. g4 — FEN: r2r2k1/pp1b1pp1/2n1pn1p/2qpN3/5P2/2PB1N2/PP3PPP/R2QR1K1 w - - 0 14",
    idealResponse: `WOW! Bogo fearlessly weakens his own Kingside pawn structure in order to without bring another unit up for the attack. He threatens 15.g5, followed by either without ...Nh7 16.gxh6 gxh6 or 15...hxg5 16.Nxg5, both of which are bad for Black.`,
  },
  {
    id: "data-stra-int-25",
    positionType: "strategic",
    skillLevel: "intermediate",
    scenario: "Leko, Peter vs Adams, Michael — Sparkassen Gp 2 — Move 15. Qb3 — FEN: r2q1rk1/pp2bppp/2p1bn2/3n2B1/2BP4/2N2N1P/PP3PP1/R2QR1K1 w - - 4 15",
    idealResponse: `It doesn't seem to me the queen does well here; it competes with Bc4 for light squares. The idea is to combine pressure on d5 with the threat to Be7. If Black has to use Qd5 to defend d5 then what defends Be7.`,
  },
  {
    id: "data-stra-int-26",
    positionType: "strategic",
    skillLevel: "intermediate",
    scenario: "Keres vs Smyslov — Candidates Tournament — Move 15. Rxc3 — FEN: 2rq1rk1/pb2bppp/1p2p3/3p4/1nPP4/PPn2N2/1B3PPP/2RQRBK1 w - - 0 15",
    idealResponse: `White hopes to lift the rook over to the kingside for a mating attack. 15.Bxc3 Na2 16.Rc2 Nxc3 17.Rxc3 dxc4 18.bxc4 would give the advantage to Black because of his two bishops and White's weakened pawn structure.`,
  },
  {
    id: "data-stra-adv-27",
    positionType: "strategic",
    skillLevel: "advanced",
    scenario: "? vs ? — The Sicilian Najdorf: The English Attack 6.Be3 — Move 8. f3 — FEN: rn1qkb1r/1p3ppp/p2pbn2/4p3/4P3/1NN1B3/PPP2PPP/R2QKB1R w KQkq - 2 8",
    idealResponse: `One of the key ideas in the English Attack. White is planning to play g4. This move has two fundamental ideas:
a) Attack on the kingside
b) Play g5, so the knight on f6 cannot control the d5 square. The f3 move is necessary to keep the black knight away from the g4 square, preventing the knight from being exchanged for the bishop, which is unfavorable for White. [%cal Gg2g4,Rf6g4,Rf3g4]`,
  },
  {
    id: "data-stra-adv-28",
    positionType: "strategic",
    skillLevel: "advanced",
    scenario: "Instructive Game #7 Magnus Carlsen -  vs Alireza Firouzja  — The Caro Kann Defence: Complete Repertoire: Instructive Game #7 Magnus Carlsen -  - Alireza Firouzja — Move 19. Rxh4 — FEN: r2qk3/pp1nbp2/2",
    idealResponse: `I thought taking with the bishop was a given here. The bishop is now threatening f2. The bishop controlling a decent diagonal now especially preventing the queen from going to b4. The knight is in such a good spot, do we really want to move it. Though it would be threatening to take the f2 pawn with a fork, so that buys a tempo. But that tempo could be used to develop the bishop. [%csl Gb4,Gh4][%cal Ge7b4,Gd2b4,Gf5h4,Gh4f3,Gf1e2,Gh1h4]`,
  },
  {
    id: "data-stra-adv-29",
    positionType: "strategic",
    skillLevel: "advanced",
    scenario: "Instructive Game #2 Garry Kasparov -  vs Vassily Ivanchuk — The Caro Kann Defence: Complete Repertoire: Instructive Game #2 Garry Kasparov -  - Vassily Ivanchuk — Move 10. c5 — FEN: r1bq1rk1/pp1nbpp1/",
    idealResponse: `Helpful, since it removes a guard from b4 when dxc5 threatens to play b4.
Both the difficulty to play dxc5 and the pawn's lack of movement from c5 to
c6 count as weaknesses of dxc5. 
Ne5 prevents the capture of the black bishop and gives d5's queen control of
c5 and e5, allowing her to better defend d3. [%csl Gc5][%cal Gc6c5]`,
  },
  {
    id: "data-stra-adv-30",
    positionType: "strategic",
    skillLevel: "advanced",
    scenario: "Alapin, Semyon vs Rubinstein, Akiba — Prague — Move 17. c3 — FEN: r4rk1/1p2n1pp/1pp2p2/3ppP2/4P3/N2P3P/PPP3P1/R4RK1 w - - 0 17",
    idealResponse: `This creates a serious weakness on d3.  One implication is that now exd5, trying to liquidate into a slightly worse position, becomes impossible as black recaptures with a rook and puts too much pressure on the weak pawn.  Less obvious is that after black exchanges d-pawns, the square remains weak, and in fact white's entire queenside, especially the a4 and c4 squares.  This is because, with c2-c3 already played, b2-b3 creates further weaknesses.  Nonetheless, it was already difficult for white, and the idea to get his knight into play seemed reasonable.`,
  },
  {
    id: "data-endg-beg-31",
    positionType: "endgame",
    skillLevel: "beginner",
    scenario: "? vs ? — Trap and Tactics for Beginner: Tactics 8 (Strive for a Draw!) — Move 3. Ke8 — FEN: 3k4/4P3/3K4/8/8/8/8/8 b - - 0 3",
    idealResponse: `Good move! Now, white can't do anything and can't promote his pawn. Whichever move white will make is a draw. Want the King to move to the Ke6, Ke5, Kd5, Kc5, Kc6 or also Kc7. All that movement is a draw. A Chess Master says: "That the most important part of the game between losing, winning or drawing is the endgame. The endgame must be carefully thought out to move towards victory and to move towards a draw in playing chess." That is why the end game is so important to learn and understand in everyone. Thank you for learning the tactical tactics of this end game. Hopefully the tactics are very useful for you or all chess players. :)`,
  },
  {
    id: "data-endg-beg-32",
    positionType: "endgame",
    skillLevel: "beginner",
    scenario: "? vs ? — Knights | How to dominate your opponents!: Bishop dominating a knight — Move 1. Bc5 — FEN: 2n4k/5ppp/8/K7/8/4B3/5PPP/8 w - - 0 1",
    idealResponse: `With this simple move, the knight is completely paralyzed! Black has no way to stop the plan of Ka6, Kb7, Kxc8.
PRO TIP: Placing a bishop exactly three squares away from a knight dominates the knight. Every forward knight move is covered by the bishop. This is sometimes also called "offsetting a knight." [%csl Ga7,Gb6,Gd6,Ge7][%cal Bc5a7,Gc8e7,Gc8d6,Gc8b6,Gc8a7,Bc5e7]`,
  },
  {
    id: "data-endg-int-33",
    positionType: "endgame",
    skillLevel: "intermediate",
    scenario: "Do's and Don'ts - White's Perspective vs Middlegame Plan #7 — The Caro Kann Defence: Complete Repertoire: DO's and DON'TS - White's Perspective - Middlegame Plan #7 — Move 34. f4 — FEN: 3k4/1p4R1/pPbN",
    idealResponse: `!! The decisive coup. White's small but highly efficient army is ready to concentrate its powers and deal the death blow. If now 34...Rxd4, then 35 f5 exf5 36 e6 Re4+ 37 Nxe4 fxe4 38 Rc7, threatening Rxc6, and if 37...Bb5+, 38 Ke3 when Black's b-pawn is doomed and White's king penetrates. [%csl Gf4][%cal Gf2f4]`,
  },
  {
    id: "data-endg-int-34",
    positionType: "endgame",
    skillLevel: "intermediate",
    scenario: "W38 vs B38 — Analyzed Games — Move 38. Ke4 — FEN: 8/4k1p1/5p1p/2p2K2/1pB2P2/1P4P1/7P/3n4 w - - 6 38",
    idealResponse: `Dubious. This allows black to consilidate. Better was 
39. Kg6 Ne3 40. Bd3 (Kxg7?? 40. ... Nxc4 wins for black) Kf8 
41. h3, and it's hard to see how black will make progress.`,
  },
  {
    id: "data-endg-int-35",
    positionType: "endgame",
    skillLevel: "intermediate",
    scenario: "Psakhis, Lev vs Polgar, Judit — Superstars Hotel Bali — Move 49. Kg3 — FEN: 8/p7/Pb3p2/6p1/5kPp/5P1P/PK6/1B6 b - - 0 49",
    idealResponse: `studiously avoiding Pf3 because it actually blocks White's bishop on the e4-h1 diagonal. When Ph3 is gone Ph4 will need to promote on h1, so it's better if White's bishop can't guard h1 from e4.`,
  },
  {
    id: "data-endg-int-36",
    positionType: "endgame",
    skillLevel: "intermediate",
    scenario: "Ponomariov,R vs Karpov,An — GMA, Wijk aan Zee NED — Move 50. a5 — FEN: 8/p4pk1/3R1b2/1p6/3PB1K1/1P2rP2/P7/8 b - - 3 50",
    idealResponse: `White was threatening Rd6-a6xa7, so he had to move the pawn onto a safer square. Black would like to play ...b5-b4 to fix White's pawns and then ...Re3-e2 would grab at least one.`,
  },
  {
    id: "data-endg-adv-37",
    positionType: "endgame",
    skillLevel: "advanced",
    scenario: "Ivanchuk, Vassily vs Adams, Michael — SuperGM — Move 43. d5 — FEN: 8/4nk2/Q7/7p/2PP1P2/P6r/3K3P/7b w - - 7 43",
    idealResponse: `The White pawns sort of cut Black's "army" in half. Bh1 and Rh3 are separate from Ne7 and Kf7. At the moment White's Kd2 is also separated from the area where Qa6 can play offense, but with Pd5 it doesn't matter. Black's king and knight can't defend against White's queen and pawn. This forces a crisis upon Black; he has to get rid of Pd5.`,
  },
  {
    id: "data-endg-adv-38",
    positionType: "endgame",
    skillLevel: "advanced",
    scenario: "Lasker,Em vs Lasker,Ed — New York — Move 83. Kf3 — FEN: 8/8/6P1/2k5/4KP2/1p6/1N1r4/8 w - - 3 83",
    idealResponse: `...but White realizes that it's not much of a threat (see the variation to without Black's next move). White moves his King to control f2 and g2, preventing without mischief against his passed pawns.`,
  },
  {
    id: "data-endg-adv-39",
    positionType: "endgame",
    skillLevel: "advanced",
    scenario: "Vaiser vs Kasparov — Moscow — Move 40. h5 — FEN: 8/5pkp/6p1/1pR5/p1b2P2/P3R1K1/1r6/8 b - - 2 40",
    idealResponse: `Here the game was adjourned, but White, having sealed 41.Kh4, resigned before resumption. One could argue with this, but Black does have a clear path to victory. For example (see variation). 40...h5 41.Kh4 Rb3 42.Rg3 Rb1 43.Re3 Rg1 44.Rg5 Rh1+ 45.Kg3 f5 cutting off the rook from the queenside.`,
  },
  {
    id: "data-open-beg-40",
    positionType: "opening",
    skillLevel: "beginner",
    scenario: "LeninPerez vs ThunderPai — ðŸ‡®ðŸ‡¹ Italian Opening ðŸ‡®ðŸ‡¹: Main Ideas in the Giuoco Pianissimo — Move 1. Nbd2 — FEN: r1bq1rk1/ppp2ppp/2np1n2/2b1p3/2B1P3/2PP1N2/PP3PPP/RNBQ1RK1 w Qq - 0 1",
    idealResponse: `#IDEA 1: Bring the knight from b1 to g3. It is very important to maneuver the Knight from b1 to g3, so that it is in a better position. For this, the f1 rook must move to e1, to free the f1 square for the Knight, and then, let him jump to g3. [%csl Gg3][%cal Gd2f1,Gf1g3]`,
  },
  {
    id: "data-open-beg-41",
    positionType: "opening",
    skillLevel: "beginner",
    scenario: "? vs ? — London System Repertoire: London vs Old Benoni — Move 2. d5 — FEN: rnbqkbnr/pp1ppppp/8/2p5/3P4/8/PPP1PPPP/RNBQKBNR w KQkq - 0 2",
    idealResponse: `In this system, we will put strong pawns on d5 and e4 and our knights on c3 and f3. It is important to avoid capturing with these central pawns (unless black plays some very strange response) in order to preserve the central pawn chain. [%csl Yd5,Ye4,Bc3,Bf3]`,
  },
  {
    id: "data-open-int-42",
    positionType: "opening",
    skillLevel: "intermediate",
    scenario: "? vs ? — Catalan: Catalan, Slav — Move 5. Nc3 — FEN: rn1qkb1r/pp2pppp/2p2n2/3p1b2/2PP4/5NP1/PP2PP1P/RNBQKB1R w KQkq - 1 5",
    idealResponse: `Important: In most slav positions Nc3 is better than the standard Nd2. This is because black's light squared bishop controls c2 which where the queen normally goes in order to support e4. Because of that, we need to support e4 by playing Nc3 and Nd2 so there is more support for the e4 break. [%csl Ge4][%cal Gb1c3,Gf3d2,Gf1g2,Gg2e4,Gc3e4,Gd2e4]`,
  },
  {
    id: "data-open-int-43",
    positionType: "opening",
    skillLevel: "intermediate",
    scenario: "Alekhine vs Hromadka — Bad Pistyan — Move 17. Qb7 — FEN: r3kb1r/q2n1ppp/p7/3Pp3/Pp2N3/8/1PQ2PPP/R1B2RK1 b kq - 0 17",
    idealResponse: `17...Bc5 with the idea of castling would be met by 18.Be3 Bxe3 19.Nd6+ Kf8 20.fxe3 Qxe3+ 21.Kh1 when White would have a big advantage for the lost pawn due to Black's uncastled king and better development.`,
  },
  {
    id: "data-open-int-44",
    positionType: "opening",
    skillLevel: "intermediate",
    scenario: "Danailov vs Kasparov — World Junior Championship Dortmund — Move 10. Nd5 — FEN: r1br2k1/pppn1pbp/5np1/4p1B1/2P1P3/2N2N2/PP2BPPP/R3K2R w KQ - 2 10",
    idealResponse: `With the idea of exchanging off as many pieces as possible. However, this takes time and allows Black a slight advantage. Better was 10.O-O-O Rf8 11.Rhe1 c6 12.Nd2 Nc5 13.f3 a5 when it's unclear is Black can make anything of the hole on d4.`,
  },
  {
    id: "data-open-int-45",
    positionType: "opening",
    skillLevel: "intermediate",
    scenario: "Larsen vs Spassky — USSR vs. World — Move 10. f4 — FEN: 2kr3r/ppp1qppp/2p2n2/2b2b2/2P1p3/1P2P3/PBQPBPPP/RN2K2R w KQ - 5 10",
    idealResponse: `This is a  major mistake, because the king's position is weakened. But Larsen may have been getting a little desperate, because Black already had the advantage in development. 10.Bxf6 Qxf6 11.Nc3 Qe5 12.O-O h5 Black has a strong attack.`,
  },
  {
    id: "data-open-adv-46",
    positionType: "opening",
    skillLevel: "advanced",
    scenario: "? vs ? — üõ°Ô∏èThe Slav Defenseüõ°Ô∏è: Modern Slav‚ö° — Move 4. Bg2 — FEN: rn1qkb1r/pp3ppp/2p1pn2/5b2/2QP4/5NP1/PP2PP1P/RNB1KB1R w KQkq - 0 4",
    idealResponse: `This is the Modern Slav, very tricky. It is not great, but if you play against an opponent who is not ready you have better chances of winning. Your plans are Nbd2, Be7 followed by 0-0, and Qc7 finnishing development and connecting the rooks and bringing them into the center. In the middlgame, try going for the break e5. You have a nice Caro-Kann structure, very solid :D [%csl Rg2,Bd7,Be7,Bg8,Ye5,Bc7][%cal Rf1g2,Bb8d7,Bf8e7,Be8g8,Ye6e5,Bd8c7]`,
  },
  {
    id: "data-open-adv-47",
    positionType: "opening",
    skillLevel: "advanced",
    scenario: "W34 vs B34 — Analyzed Games — Move 7. c5 — FEN: rn1qkb1r/pp3ppp/2p1pn2/3p4/4P3/2NP1Q1P/PPPB1PP1/R3KB1R b KQkq - 2 7",
    idealResponse: `While not objectively unsound, 7....c5 invites many
problems. Here the problem again is the lack of
development. Typically in these pawn positions Black
is going to want to play ...Bd6 and ...Nd7 before ...c5. 
Even stronger is if Black can also achieve a Rook on
the c - file. Now consider the possibilities of 7....
Nbd7 8. O-O-O Bd6. Now Black can try to "clear and
seal" with ...c5 and ...d4. The concept involves clearing
the Knight from it's defensive post and using the pawn
structure to seal off the opponents pieces on the
opposite side of the board. This takes courage
because you will need to castle on the opposite side
and attack without counting the cost (sacrifice almost
everything if necessary). However, you do get to
isolate the King away from any reinforcements.`,
  },
  {
    id: "data-open-adv-48",
    positionType: "opening",
    skillLevel: "advanced",
    scenario: "Fischer vs Spassky — Sveti Stefan — Move 8. c5 — FEN: r1bqk1nr/p2p1pbp/2p3p1/4p3/1p2P3/P4N2/2PP1PPP/RNBQR1K1 b kq - 0 8",
    idealResponse: `8...d6 9.axb4 Ne7 10. h3 O-O 11.d3 gives White a slightly better position, because there are some weaknesses in Black's position. But 8...bxa3 9.Bxa3 d6 gives White sufficient compensation for the pawn, but how much more?`,
  },
  {
    id: "data-stra-adv-49",
    positionType: "strategic",
    skillLevel: "advanced",
    scenario: "Kmoch vs Alekhine — Vienna — Move 13. g3 — FEN: r2qk2r/ppbn1p2/2p1p3/2P2bpp/1P1PpP2/4P3/P2NB1PP/R1BQ1RK1 w kq - 0 13",
    idealResponse: `This slow defending move allows Black a winning initiative. 13.Nc4 Nf6 14.Ne5 gxf4 15.exf4 Although Black would still retain the better chances due to the weakness of White's pawn on d4.`,
  },
  {
    id: "data-open-adv-50",
    positionType: "opening",
    skillLevel: "advanced",
    scenario: "Gligoric, S vs Bidev, P — Move 4. Ba4 — FEN: r1bqkbnr/1ppp1ppp/p1n5/1B2p3/4P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 0 4",
    idealResponse: `The answer is that White is not actually threatening -- yet -- to take the N/c6 and grab the e-pawn. Even in the exchange variation 3...a6 4.Bxc6, White's aim is not to win the e-pawn but rather to establish a healthy Kingside pawn majority, at the cost of the two Bishops. 4...dxc6 The punishment for grabbing on e5 is a swift equalization of the position: 5.Nxe5 Qd4 6.Nf3 Qxe4+ 7.Qe2 Qxe2+ 8.Kxe2.  Notice the resulting pawn structure. White and Black each have four pawns on the Queenside. In this kind of pawn formation, White cannot force a passed pawn: Black's "crippled" Queenside holds White's "healthy" set of four easily. So Black has the Bishop pair essentially for free. Unfortunately, it's almost inevitable that everything will be exchanged down the e-file (both sides will rush to occupy this with Rooks) with an early draw the likely result. 
So instead of playing 4.Bxc6 as a means of "winning" the e-pawn, White sometimes plays the exchange variation in order to trade his own d-pawn for Black's e-pawn. That is a different matter entirely: 5.0-0 Bd6 6.d4 exd4 7.Qxd4  This sort of position -- with or without the exchange of Queens -- affords White more winning chances. Now White's pawn majority is on the Kingside, and that makes a huge difference. Experience shows that Black's pair of Bishops is just about adequate compensation for White's pawn majority. But this line can definitely be played for something other than a stone-cold draw, as Fischer proved numerous times. 
Nevertheless, the resulting positions often lack the dynamism of a full-board struggle. In our game, Gligoric chooses a time-honored move that remains the main line of the Ruy Lopez: 4.Ba4  It's instructive to keep track of time in the opening. White is moving the Bishop for the second time, but this isn't really a net loss in development since Black's move ...a6 hardly counts for much in the way of time. White remains, then, half a tempo ahead. 
I can hear the faint sound of heads being scratched. "Half a tempo? How do you get half of a tempo? A move is a move, you can't have half of a move!"  Not to leave you wondering, here's my modest contribution toward the theory of time in the opening. In the initial position of chess, White is thought to have a slight advantage. But why? The position is, after all, symmetrical. White's only advantage is that it is his turn to move.   Now, it would violate logic if White, who has this theoretical advantage, were to stand worse after using it in the best possible way. Therefore, I propose to count having the turn to move as being worth half of a tempo. Consider: 
After 1.e4, White has moved -- and gets a full tempo for that. But it is now Black's turn to play, and so Black gets back half a tempo. The net difference? One half of a tempo, just as it was before White moved. Skip forward now to the point where White has played 4.Ba4. 
White has three useful moves on the board that affect, directly or indirectly, the center: P/e4, N/f3, B/a4 (threatening Black's Knight, though at the moment that threat doesn't carry much bite).  Black has only two: N/c6 and P/e5. However, it is Black's turn to move. So White has retained his half-tempo lead. (White gets 3 tempi, one for each "good" move. Black gets two for "good" moves and another half-tempo for its being his turn to move.)`,
  },
  {
    id: "data-stra-adv-51",
    positionType: "strategic",
    skillLevel: "advanced",
    scenario: "Shirov, Alexei vs Ivanchuk, Vassily — SuperGM — Move 11. c3 — FEN: r2qrbk1/1bpp1ppp/p1n2n2/1p2p3/P3P3/1B1P1N2/1PPN1PPP/R1BQR1K1 w - - 3 11",
    idealResponse: `This is a useful move for several purposes: one is to prevent ...Nc6-d4; another is to allow Qd1 to defend Pa4, so that after ...Nc6-a5 White can retreat Bb3-a2 (on the better diagonal) without losing Pa4. He may have some idea of playing d3-d4, but at the moment that would probably help Black more than White. White would rather maneuver Nd2-f1-g3 (defending Pe4 again) before committing to d3-d4 (which would weaken Pe4) .`,
  },
  {
    id: "data-tact-int-52",
    positionType: "tactical",
    skillLevel: "intermediate",
    scenario: "W12 vs B12 — Analyzed Games — Move 28. Qb1 — FEN: 4r2r/1pp5/p2pk2p/4pRn1/1nP5/NP2P1P1/P1Q3KP/R7 w - - 1 28",
    idealResponse: `Too passive. Qf2! is natural and strong. Remember with your 
heavy pieces (rooks & queens), have them double on an open 
column, or file. What might happen is 28. Qf2 Ne4 29. Qf3 Ng5 
30. Qg4 (threatening Rxg5, discovered check!) Ke7 31. Raf1, 
getting nearly all white's pieces into the attack. The only 
straggler is that knight at a3, but he can be rerouted by Nb1- c3.`,
  },
  {
    id: "data-stra-adv-53",
    positionType: "strategic",
    skillLevel: "advanced",
    scenario: "? vs ? — ♟ Sicilian Defense ♟: Scheveningen Variation — Move 1. e6 — FEN: rnbqkb1r/pp2pppp/3p1n2/8/3NP3/2N5/PPP2PPP/R1BQKB1R b KQkq - 0 1",
    idealResponse: `The Scheveningen variant is perhaps, the main line of the Sicilian defense.
Black secures the central squares to hasten to deploy his pieces and prepare the advance ... d5 which is not possible at the moment due to its development delay.
On the other hand, White tends to play aggressively complicating the middlegame, because if not in the endgame Black is better because of its better pawn structure and especially, because of the power of the c-file and the pressure exerted by the minority attack. with ... b5-b4. [%csl Gf5,Ge5,Gd5,Gc5][%cal Gd6e5,Ge6d5,Gd6c5,Ge6f5]`,
  },
  {
    id: "data-stra-adv-54",
    positionType: "strategic",
    skillLevel: "advanced",
    scenario: "? vs ? — Sicilian Defense üõ†Ô∏è Practiceüõ†Ô∏è: ‚ôüScheveningen Variation‚ôü — Move 5. e6 — FEN: rnbqkb1r/pp2pppp/3p1n2/8/3NP3/2N5/PPP2PPP/R1BQKB1R b KQkq - 2 5",
    idealResponse: `Although not as popular as the others, Kasparov played this defense a lot.
Yes, 5.e6! Black secures the central squares to hasten to deploy his pieces and prepare the advance ... d5 which is not possible at the moment due to its development delay.
On the other hand, White tends to play aggressively complicating the middlegame, because if not in the endgame Black is better because of its better pawn structure and especially, because of the power of the c-file and the pressure exerted by the minority attack. with ... b5-b4. [%csl Ge5,Gf5,Gd5,Gc5][%cal Ge6d5,Gd6c5,Gd6e5,Ge6f5]`,
  },
  {
    id: "data-stra-adv-55",
    positionType: "strategic",
    skillLevel: "advanced",
    scenario: "? vs ? — The Sicilian Najdorf: The Positional Variation: 6.Be2 — Move 11. Nd5 — FEN: r2q1rk1/1p1nbppp/p2pbn2/4p3/4P3/1NNQB3/PPP1BPPP/R4RK1 w - - 8 11",
    idealResponse: `White is planning to play c4 on the next move, so Black is forced to capture on d5. Another reason for White to place the queen on d3 is because the queen controls the f5 square, so Black cannot take on d5 with the knight and play Bf5 afterwards. The d5 square is very important in the Sicilian Najdorf.
By playing e5, the d5 square is weakened and the white knight may think about positioning himself on that square and, among other things, the queen cannot go to its standard c7 square. [%csl Bd5]`,
  },
  {
    id: "data-open-adv-56",
    positionType: "opening",
    skillLevel: "advanced",
    scenario: "Kamsky, G vs Karpov, An — ? — Move 11. Qh4 — FEN: r1bqk2r/pp3pp1/2pbpn1p/8/3PQ3/3B1N2/PPP2PPP/R1B1K2R w KQkq - 1 11",
    idealResponse: `Up until now, the queen almost automatically retreated to e2, for example, Sokolov played this against me once (Belfort 1988). This game turned out in white's favor and is
annotated by Beliavsky (Game 23).
On 11.Qh4, theory indicates 11...Nd5, but after 12.Qxd8+ Kxd8 13.c3,white has a small positional advantage, and more importantly, black has little play.
After 11...Qa5+ 12.Bd2 Qh5 13.Qxh5 Nxh5 14.Ne5! 0-0 15.0-0-0, black also does not have enough counterplay (Hector-Hodgson, London 1991): 15...c5 (better is 15...Nf6) 16.g4 Nf6 17.g5! hxg5 18.Bxg5 Nd5 (if 18...cxd4 19.Bxf6 gxf6 20.Rdg1+ Kh8 21.Rg3! Be5 22.Rh3+ and Rg1+) 19.Nc4 Bc7 20.dxc5, with a noticeable white advantage.
Of course, 11...0-0 is bad because of the standard 12.Bxh6! gxh6 13.Qxh6, after which black will not survive; 14.Ng5 is enough of a threat.`,
  },
  {
    id: "data-open-adv-57",
    positionType: "opening",
    skillLevel: "advanced",
    scenario: "Kamsky, G vs Karpov, An — ? — Move 11. Qh4 — FEN: r1bqk2r/pp3pp1/2pbpn1p/8/3PQ3/3B1N2/PPP2PPP/R1B1K2R w KQkq - 1 11",
    idealResponse: `Up until now, the queen almost automatically retreated to e2, for example, Sokolov played this against me once (Belfort 1988). This game turned out in white's favor and is
annotated by Beliavsky (Game 23).
On 11.Qh4, theory indicates 11...Nd5, but after 12.Qxd8+ Kxd8 13.c3,white has a small positional advantage, and more importantly, black has little play.
After 11...Qa5+ 12.Bd2 Qh5 13.Qxh5 Nxh5 14.Ne5! 0-0 15.0-0-0, black also does not have enough counterplay (Hector-Hodgson, London 1991): 15...c5 (better is 15...Nf6) 16.g4 Nf6 17.g5! hxg5 18.Bxg5 Nd5 (if 18...cxd4 19.Bxf6 gxf6 20.Rdg1+ Kh8 21.Rg3! Be5 22.Rh3+ and Rg1+) 19.Nc4 Bc7 20.dxc5, with a noticeable white advantage.
Of course, 11...0-0 is bad because of the standard 12.Bxh6! gxh6 13.Qxh6, after which black will not survive; 14.Ng5 is enough of a threat.`,
  },
  {
    id: "data-tact-adv-58",
    positionType: "tactical",
    skillLevel: "advanced",
    scenario: "Chapter #24: vs Fantasy-Tarkatower Variation: Main Line #1 — The Caro Kann Defence: Complete Repertoire: Chapter #24: - Fantasy-Tarkatower Variation: Main Line #1 — Move 7. Bh5 — FEN: rn1qkb1r/pp3ppp/",
    idealResponse: `Bh5 adding another defender on the f7 pawn. Problem with other moves such
as lets say Nbd7. White has this horrendous threat of Qb3! Attacking the b7
pawn and the f7 pawn. Black would be left with no choice but to defend the f7 pawn but the b7 pawn will hang thus white would have a terrific control
of the 7th Rank. [%csl Gh5][%cal Gg4h5]`,
  },
  {
    id: "data-stra-adv-59",
    positionType: "strategic",
    skillLevel: "advanced",
    scenario: "Instructive Game #9 Garry Kasparov -  vs Anatoly Karpov — The Caro Kann Defence: Complete Repertoire: Instructive Game #9 Garry Kasparov -  - Anatoly Karpov — Move 13. Ne5 — FEN: r1b1k2r/pp2qpp1/1n2pn",
    idealResponse: `Queen e7 and now Kasparov plays d takes e5 so he's capturing away from
the center he has the idea that to play Knight e5 now because he's going to
reinforce that knight fon e5. He's lost quite a few moves all these 
Fancy light maneuvers but it has provoked a weakness in blacks position with
this h6 and black is also quite uncomfortable on Queen side potentially as we'll see Bishop d7 Knight gf3 [%csl Ge5][%cal Gf3e5]`,
  },
  {
    id: "data-open-int-60",
    positionType: "opening",
    skillLevel: "intermediate",
    scenario: "? vs ? — ���� Sicilian Kan Repertoire ����: Rare Sidelines — Move 3. Bc4 — FEN: rnbqkbnr/pp1p1ppp/4p3/2p5/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 0 3",
    idealResponse: `Surprisingly common amongst beginner and intermediate players. When starting out, players are taught the Italian Game (e4 e5 Nf3 Nc6 Bc4) which is a great opening to learn piece development and center control. But these moves are not automatic. I'll be blunt, but against the Kan, it is just plain bad. The a2-g8 diagonal is already closed, so the bishop is not going places on c4. To make matters worse, d5 comes with tempo!`,
  },